export const FETCH_SCHEDULES = 'FETCH_SCHEDULES';
export const FETCH_SCHEDULES_PENDING = 'FETCH_SCHEDULES_PENDING';
export const FETCH_SCHEDULES_FULFILLED = 'FETCH_SCHEDULES_FULFILLED';
export const FETCH_SCHEDULES_REJECTED = 'FETCH_SCHEDULES_REJECTED';

export const ADD_SCHEDULE = 'ADD_SCHEDULE';
export const ADD_SCHEDULE_PENDING = 'ADD_SCHEDULE_PENDING';
export const ADD_SCHEDULE_FULFILLED = 'ADD_SCHEDULE_FULFILLED';
export const ADD_SCHEDULE_REJECTED = 'ADD_SCHEDULE_REJECTED';

export const SET_SCHEDULE_STATUS = 'SET_SCHEDULE_STATUS';
export const SET_SCHEDULE_STATUS_PENDING = 'SET_SCHEDULE_STATUS_PENDING';
export const SET_SCHEDULE_STATUS_FULFILLED = 'SET_SCHEDULE_STATUS_FULFILLED';
export const SET_SCHEDULE_STATUS_REJECTED = 'SET_SCHEDULE_STATUS_REJECTED';

export const SET_SCHEDULE_VISIBILITY_FILTER = 'SET_SCHEDULE_VISIBILITY_FILTER';