export const SHOW_SCHEDULED = 'SHOW_SCHEDULED';
export const SHOW_WAITING = 'SHOW_WAITING';
export const SHOW_ENGAGED = 'SHOW_ENGAGED';
export const SHOW_COMPLETED = 'SHOW_COMPLETED';

export const SCHEDULE_STATUS_SCHEDULED = "SCHEDULED"
export const SCHEDULE_STATUS_WAITING = "WAITING"
export const SCHEDULE_STATUS_ENGAGED = "ENGAGED"
export const SCHEDULE_STATUS_COMPLETED = "COMPLETED"
